# Generated by Django 5.2.6 on 2025-09-25 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocorrencias', '0004_ocorrencia_data_reabertura_ocorrencia_ip_reabertura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAcidenteTransito',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ocorrencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_acidente_transito', serialize=False, to='ocorrencias.ocorrencia')),
                ('endereco_completo', models.CharField(blank=True, max_length=400, verbose_name='Endereço Completo')),
                ('coordenadas', models.CharField(blank=True, max_length=50, verbose_name='Coordenadas GPS')),
                ('is_endereco_nao_localizado', models.BooleanField(default=False, verbose_name='Endereço Não Localizado?')),
                ('is_veiculo_oficial', models.BooleanField(default=False, verbose_name='Veículo Oficial Envolvido?')),
                ('orgao_veiculo_oficial', models.CharField(blank=True, max_length=100, verbose_name='Órgão Vinculado ao Veículo')),
                ('auxiliar', models.ForeignKey(blank=True, limit_choices_to={'perfil': 'OPERACIONAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_acidente_como_auxiliar', to=settings.AUTH_USER_MODEL, verbose_name='Auxiliar Operacional')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Acidente de Trânsito',
            },
        ),
        migrations.CreateModel(
            name='FichaConstatacaoSubstancia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ocorrencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_constatacao_substancia', serialize=False, to='ocorrencias.ocorrencia')),
                ('material_encontrado_em_poder_de', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Constatação em Substância',
            },
        ),
        migrations.CreateModel(
            name='FichaDocumentoscopia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ocorrencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_documentoscopia', serialize=False, to='ocorrencias.ocorrencia')),
                ('material_encontrado_em_poder_de', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Documentoscopia / SPMD',
            },
        ),
        migrations.CreateModel(
            name='FichaIdentificacaoVeicular',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ocorrencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_identificacao_veicular', serialize=False, to='ocorrencias.ocorrencia')),
                ('endereco_completo', models.CharField(blank=True, max_length=400, verbose_name='Local de Encontro do Veículo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Identificação Veicular',
            },
        ),
        migrations.CreateModel(
            name='FichaLocalCrime',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ocorrencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_local_crime', serialize=False, to='ocorrencias.ocorrencia')),
                ('endereco_completo', models.CharField(blank=True, max_length=400, verbose_name='Endereço Completo')),
                ('coordenadas', models.CharField(blank=True, max_length=50, verbose_name='Coordenadas GPS')),
                ('local_fechado', models.BooleanField(default=False, verbose_name='Local Fechado')),
                ('endereco_nao_localizado', models.BooleanField(default=False, verbose_name='Endereço Não Localizado')),
                ('local_preservado', models.BooleanField(default=True, verbose_name='Local Preservado')),
                ('observacoes_local', models.TextField(blank=True, verbose_name='Observações Gerais do Local')),
                ('condicoes_climaticas', models.CharField(blank=True, max_length=100, verbose_name='Condições Climáticas')),
                ('iluminacao', models.CharField(blank=True, choices=[('NATURAL', 'Luz Natural'), ('ARTIFICIAL', 'Luz Artificial'), ('MISTA', 'Mista'), ('INSUFICIENTE', 'Insuficiente')], max_length=50, verbose_name='Condições de Iluminação')),
                ('auxiliar', models.ForeignKey(blank=True, limit_choices_to={'perfil': 'OPERACIONAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_como_auxiliar', to=settings.AUTH_USER_MODEL, verbose_name='Auxiliar Operacional')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Local de Crime',
            },
        ),
        migrations.CreateModel(
            name='FichaMaterialDiverso',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ocorrencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_material_diverso', serialize=False, to='ocorrencias.ocorrencia')),
                ('lacre_recebimento', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição (Específica)')),
                ('material_encontrado_em_poder_de', models.CharField(blank=True, max_length=255)),
                ('nome_doador_local_vestigio', models.CharField(blank=True, max_length=255, verbose_name='Nome do Doador / Local do Vestígio (LGF/LBF)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Material, Objeto, Vestígios (Balística, etc.)',
            },
        ),
        migrations.CreateModel(
            name='ItemDocumentoscopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descricao_material', models.TextField()),
                ('lacre_recebimento', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_documentoscopia', to='fichas.fichadocumentoscopia')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Documentoscopia',
            },
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_material', to='fichas.fichamaterialdiverso')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Material',
            },
        ),
        migrations.CreateModel(
            name='ItemSubstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('substancia', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=50)),
                ('massa_bruta', models.DecimalField(decimal_places=3, max_digits=10)),
                ('massa_retirada_exame', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('massa_retirada_contraprova', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('massa_liquida_devolvida', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_substancia', to='fichas.fichaconstatacaosubstancia')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Substância',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('chassi', models.CharField(blank=True, max_length=40)),
                ('motor', models.CharField(blank=True, max_length=40)),
                ('cambio', models.CharField(blank=True, max_length=40)),
                ('renavam', models.CharField(blank=True, max_length=20)),
                ('ano_modelo', models.CharField(blank=True, max_length=10)),
                ('cor', models.CharField(blank=True, max_length=30)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('ficha_acidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='fichas.fichaacidentetransito')),
                ('ficha_identificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='fichas.fichaidentificacaoveicular')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veículo',
            },
        ),
        migrations.CreateModel(
            name='Vestigio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_numero', models.PositiveIntegerField(verbose_name='Item Nº')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada do Vestígio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('ficha_local_crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestigios', to='fichas.fichalocalcrime')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vestígio Coletado',
                'ordering': ['item_numero'],
                'unique_together': {('ficha_local_crime', 'item_numero')},
            },
        ),
        migrations.CreateModel(
            name='Lacre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RECEBIMENTO', 'Recebimento'), ('DEFINITIVO', 'Definitivo'), ('DEVOLUCAO', 'Devolução'), ('CONTRAPROVA', 'Contraprova'), ('TRANSPORTE', 'Transporte'), ('TEMPORARIO', 'Temporário')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('item_substancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lacres', to='fichas.itemsubstancia')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vestigio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lacres', to='fichas.vestigio')),
            ],
            options={
                'verbose_name': 'Lacre',
            },
        ),
        migrations.CreateModel(
            name='Vitima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Vítima')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('ficha_acidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitimas', to='fichas.fichaacidentetransito')),
                ('ficha_local_crime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitimas', to='fichas.fichalocalcrime')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vítima',
            },
        ),
    ]
