# Generated by Django 5.2.6 on 2026-03-17 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criou', 'Criou'), ('editou', 'Editou'), ('deletou', 'Deletou')], max_length=10, verbose_name='Ação')),
                ('app_label', models.CharField(max_length=50, verbose_name='Módulo (interno)')),
                ('modelo', models.CharField(max_length=100, verbose_name='Entidade')),
                ('objeto_id', models.CharField(max_length=100, verbose_name='ID do Objeto')),
                ('objeto_repr', models.CharField(max_length=250, verbose_name='Descrição do Objeto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
