# Generated by Django 5.2.6 on 2026-05-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0001_initial'),
        ('procedimentos_cadastrados', '0003_alter_procedimentocadastrado_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestigio',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, related_name='vestigios_custodia', to='procedimentos_cadastrados.procedimentocadastrado'),
        ),
        migrations.DeleteModel(
            name='ProcedimentoCustodia',
        ),
    ]
