# Generated by Django 5.2.6 on 2026-05-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0002_alter_vestigio_procedimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestigio',
            name='responsavel_nome',
            field=models.CharField(blank=True, help_text='Nome do responsável pelo registro — usado quando created_by não está disponível.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vestigiomovimentacao',
            name='responsavel_nome',
            field=models.CharField(blank=True, help_text='Nome do responsável — usado quando created_by não está disponível.', max_length=255, null=True),
        ),
    ]
