# Generated by Django 5.2.6 on 2026-05-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0003_vestigio_responsavel_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='foto',
            field=models.ImageField(blank=True, help_text='Fotografia do coletado (JPG/PNG). Opcional.', null=True, upload_to='custodia/dna/fotos/'),
        ),
    ]
