# Generated by Django 5.2.6 on 2026-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0004_dna_foto'),
        ('ocorrencias', '0015_ocorrencia_laudo_entregue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestigio',
            name='ocorrencias_vinculadas',
            field=models.ManyToManyField(blank=True, related_name='vestigios', to='ocorrencias.ocorrencia', verbose_name='Ocorrências Vinculadas'),
        ),
    ]
