# Generated by Django 5.2.6 on 2026-06-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0005_add_ocorrencias_vinculadas_to_vestigio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestigio',
            name='motivo_finalizacao',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
