# Generated by Django 5.2.6 on 2026-06-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0008_fichavestigioregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavestigioregistro',
            name='conteudo_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
