# Generated by Django 5.2.6 on 2025-09-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='ip_registro',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço de IP do Registro'),
        ),
    ]
