# Generated by Django 5.2.6 on 2026-01-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_movimentacao_ip_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='visualizado_admin',
            field=models.BooleanField(default=False, verbose_name='Visualizado pelo Administrativo'),
        ),
    ]
