# Generated by Django 5.2.6 on 2026-06-06 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoridades', '0001_initial'),
        ('custodia', '0008_fichavestigioregistro'),
        ('ocorrencias', '0015_ocorrencia_laudo_entregue'),
        ('procedimentos_cadastrados', '0003_alter_procedimentocadastrado_ano'),
        ('unidades_demandantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('tipo_entrega', models.CharField(choices=[('MATERIAL', 'Material Examinado'), ('LAUDO', 'Laudo Pericial'), ('MATERIAL_E_LAUDO', 'Material e Laudo')], default='MATERIAL', max_length=20, verbose_name='Tipo de Entrega')),
                ('lacre_na_entrega', models.CharField(blank=True, help_text='Snapshot do lacre vigente no momento da emissão.', max_length=255, verbose_name='Lacre na Entrega')),
                ('descricao_material', models.TextField(verbose_name='Descrição do Material')),
                ('entregue_por_nome', models.CharField(max_length=255, verbose_name='Nome do Entregador')),
                ('entregue_por_cargo', models.CharField(max_length=100, verbose_name='Cargo do Entregador')),
                ('entregue_por_cpf', models.CharField(max_length=14, verbose_name='CPF do Entregador')),
                ('entregue_em', models.DateTimeField(verbose_name='Data/Hora da Entrega')),
                ('recebido_por_nome', models.CharField(max_length=255, verbose_name='Nome do Recebedor')),
                ('recebido_por_cargo', models.CharField(max_length=100, verbose_name='Cargo do Recebedor')),
                ('recebido_por_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do Recebedor')),
                ('recebido_por_matricula', models.CharField(blank=True, max_length=50, verbose_name='Matrícula do Recebedor')),
                ('recebido_em', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Recebimento')),
                ('status_recebimento', models.CharField(choices=[('PENDENTE', 'Pendente de Recebimento'), ('ASSINADO_ELETRONICAMENTE', 'Assinado Eletronicamente'), ('ASSINADO_MANUAL', 'Assinado Manualmente')], default='PENDENTE', max_length=30, verbose_name='Status do Recebimento')),
                ('protocolo_hash', models.CharField(max_length=32, unique=True, verbose_name='Hash de Autenticidade')),
                ('vestigio_foi_finalizado', models.BooleanField(default=False, help_text='True quando este protocolo acionou a finalização automática do vestígio.', verbose_name='Vestígio Finalizado pelo Protocolo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('autoridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='autoridades.autoridade', verbose_name='Autoridade Demandante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('entregue_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Entregue Por (FK)')),
                ('ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_saida', to='ocorrencias.ocorrencia', verbose_name='Ocorrência')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos', to='procedimentos_cadastrados.procedimentocadastrado', verbose_name='Procedimento')),
                ('recebido_por_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebedor (usuário do sistema)')),
                ('unidade_demandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='unidades_demandantes.unidadedemandante', verbose_name='Unidade Demandante')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vestigio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='custodia.vestigio', verbose_name='Vestígio')),
            ],
            options={
                'verbose_name': 'Protocolo de Entrega',
                'verbose_name_plural': 'Protocolos de Entrega',
                'ordering': ['-created_at'],
            },
        ),
    ]
