# Generated by Django 5.2.6 on 2025-10-09 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoridades', '0001_initial'),
        ('ocorrencias', '0006_historicovinculacao'),
        ('procedimentos_cadastrados', '0002_alter_procedimentocadastrado_numero'),
        ('tipos_documento', '0001_initial'),
        ('unidades_demandantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_os', models.CharField(editable=False, max_length=20, unique=True)),
                ('prazo_dias', models.PositiveIntegerField(verbose_name='Prazo para Conclusão (em dias)')),
                ('texto_padrao', models.TextField(default='O DIRETOR, NO USO DE SUAS ATRIBUIÇÕES LEGAIS, EMITE A PRESENTE ORDEM DE SERVIÇO, DETERMINANDO A REALIZAÇÃO DOS EXAMES E CONFECÇÃO DO LAUDO PERICIAL.', editable=False)),
                ('status', models.CharField(choices=[('AGUARDANDO_CIENCIA', 'Aguardando Ciência'), ('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('VENCIDA', 'Vencida'), ('CONCLUIDA', 'Concluída')], default='AGUARDANDO_CIENCIA', max_length=20)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes_administrativo', models.TextField(blank=True, help_text='Observações internas sobre esta OS (não aparecem no PDF oficial)', verbose_name='Observações do Administrativo')),
                ('justificativa_atraso', models.TextField(blank=True, help_text='Justificativa do perito em caso de atraso na entrega', verbose_name='Justificativa de Atraso')),
                ('numero_reiteracao', models.PositiveIntegerField(default=0, help_text='0 = Original, 1 = 1ª Reiteração, etc.', verbose_name='Número da Reiteração')),
                ('numero_documento_referencia', models.CharField(blank=True, max_length=50, verbose_name='Nº do Documento de Referência')),
                ('processo_sei_referencia', models.CharField(blank=True, max_length=50, verbose_name='Processo SEI de Referência')),
                ('processo_judicial_referencia', models.CharField(blank=True, max_length=50, verbose_name='Processo Judicial de Referência')),
                ('data_primeira_visualizacao', models.DateTimeField(blank=True, help_text='Quando o perito visualizou a OS pela primeira vez (mesmo sem dar ciência)', null=True, verbose_name='Primeira Visualização')),
                ('data_ciencia', models.DateTimeField(blank=True, null=True)),
                ('ip_ciencia', models.GenericIPAddressField(blank=True, null=True)),
                ('autoridade_demandante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='autoridades.autoridade')),
                ('ciente_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='os_cientes', to=settings.AUTH_USER_MODEL, verbose_name='Perito Ciente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='ocorrencias.ocorrencia')),
                ('ordenada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='os_ordenadas', to=settings.AUTH_USER_MODEL, verbose_name='Ordenada por (Diretor/Chefe)')),
                ('os_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reiteracoes', to='ordens_servico.ordemservico', verbose_name='OS Original')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procedimentos_cadastrados.procedimentocadastrado')),
                ('tipo_documento_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_documento.tipodocumento', verbose_name='Documento de Referência')),
                ('unidade_demandante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades_demandantes.unidadedemandante')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
            },
        ),
    ]
