# Generated by Django 5.2.6 on 2025-10-12 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='concluida_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que deu baixa/concluiu esta OS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Concluída por'),
        ),
    ]
