# Generated by Django 5.2.6 on 2025-10-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_ordemservico_concluida_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_prazo',
            field=models.DateField(blank=True, help_text='Data calculada automaticamente: data_ciencia + prazo_dias', null=True, verbose_name='Data Limite'),
        ),
    ]
