# Generated by Django 5.2.6 on 2025-10-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0003_adicionar_data_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_CIENCIA', 'Aguardando Ciência'), ('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='AGUARDANDO_CIENCIA', max_length=20),
        ),
    ]
