# Generated by Django 5.2.6 on 2026-05-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0004_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_prazo_efetivo',
            field=models.DateField(blank=True, help_text='Data limite corrigida: data_prazo + dias_desconto_admin. Usada nas métricas de desempenho.', null=True, verbose_name='Data Limite Efetiva'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='dias_desconto_admin',
            field=models.PositiveIntegerField(default=0, help_text='Dias entre a entrega do laudo pelo perito e a finalização pelo administrativo. Descontados do prazo para fins de métricas.', verbose_name='Dias de Desconto Administrativo'),
        ),
    ]
