# Generated by Django 5.2.6 on 2026-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0005_adicionar_desconto_admin_e_prazo_efetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='ciencia_automatica',
            field=models.BooleanField(default=False, help_text='Ciência aplicada pelo sistema por inércia do servidor (sem ciência manual no prazo).', verbose_name='Ciência Automática (inércia)'),
        ),
    ]
