# Generated by Django 5.2.6 on 2025-09-20 20:47

import django.core.validators
import django.db.models.deletion
import procedimentos_cadastrados.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoCadastrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField(help_text='Apenas o número sequencial do procedimento.', validators=[django.core.validators.MinValueValidator(1)])),
                ('ano', models.PositiveIntegerField(default=procedimentos_cadastrados.models.ano_atual, help_text='Ano do procedimento.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('tipo_procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastros', to='procedimentos.procedimento', verbose_name='Tipo de Procedimento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimento Cadastrado',
                'verbose_name_plural': 'Procedimentos Cadastrados',
                'ordering': ['-ano', '-numero'],
                'constraints': [models.UniqueConstraint(fields=('tipo_procedimento', 'numero', 'ano'), name='unique_procedimento_cadastrado')],
            },
        ),
    ]
