# Generated by Django 5.2.6 on 2025-09-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos_cadastrados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentocadastrado',
            name='numero',
            field=models.CharField(help_text='Número do procedimento (pode conter letras e caracteres especiais).', max_length=50),
        ),
    ]
