# Generated by Django 5.2.6 on 2026-01-14 15:28

import django.core.validators
import procedimentos_cadastrados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos_cadastrados', '0002_alter_procedimentocadastrado_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentocadastrado',
            name='ano',
            field=models.PositiveIntegerField(default=procedimentos_cadastrados.models.ano_atual, help_text='Ano do procedimento.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
