# Generated by Django 5.2.6 on 2025-09-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
