# Generated by Django 5.2.6 on 2025-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_periciais', '0001_initial'),
        ('usuarios', '0002_alter_user_telefone_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='servicos_periciais',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='servicos_periciais.servicopericial', verbose_name='Serviços Periciais'),
        ),
    ]
