# Generated by Django 5.2.6 on 2025-09-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_servicos_periciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deve_alterar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
