# Generated by Django 5.2.6 on 2026-05-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_demandantes', '0001_initial'),
        ('usuarios', '0004_user_deve_alterar_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unidade_demandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='unidades_demandantes.unidadedemandante'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(blank=True, choices=[('PERITO', 'Perito'), ('ADMINISTRATIVO', 'Administrativo'), ('OPERACIONAL', 'Operacional'), ('SUPER_ADMIN', 'Super Admin'), ('CUSTODIANTE', 'Custodiante'), ('EXTERNO', 'Externo')], max_length=15, null=True),
        ),
    ]
