# Generated by Django 5.2.6 on 2026-06-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_user_unidade_demandante_alter_user_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Matrícula Funcional'),
        ),
    ]
