# Generated by Django 5.2.6 on 2025-10-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaudoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_exame', models.CharField(max_length=100)),
                ('arquivo_pdf', models.FileField(upload_to='laudos_referencia/')),
                ('texto_extraido', models.TextField(blank=True)),
                ('processado', models.BooleanField(default=False)),
                ('pasta_origem', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laudo de Referência',
                'verbose_name_plural': 'Laudos de Referência',
            },
        ),
    ]
