# Generated by Django 5.2.6 on 2025-10-19 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaudoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_exame', models.CharField(max_length=100)),
                ('arquivo_pdf', models.FileField(upload_to='laudos_referencia/')),
                ('texto_extraido', models.TextField(blank=True)),
                ('processado', models.BooleanField(default=False)),
                ('pasta_origem', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laudo de Referência',
                'verbose_name_plural': 'Laudos de Referência',
            },
        ),
        migrations.CreateModel(
            name='TemplateLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('quimico_preliminar_thc', 'Químico Preliminar - THC'), ('quimico_definitivo_thc', 'Químico Definitivo - THC')], max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('template_texto', models.TextField(help_text='Use {{variavel}} para placeholders. Ex: {{nome_perito}}, {{data_requisicao}}')),
                ('campos_obrigatorios', models.JSONField(default=list, help_text='Lista de campos que devem ser preenchidos pelo usuário')),
                ('campos_com_validacao', models.JSONField(default=dict, help_text='Ex: {"resultado": ["POSITIVO", "NEGATIVO"]}')),
                ('campos_automaticos', models.JSONField(default=list, help_text='Ex: ["ano_atual", "data_laudo_extenso"]')),
                ('exemplo_dados', models.JSONField(default=dict, help_text='Exemplo de como preencher os dados')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Laudo',
                'verbose_name_plural': 'Templates de Laudos',
                'db_table': 'ia_template_laudo',
            },
        ),
        migrations.CreateModel(
            name='LaudoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_preenchimento', models.JSONField()),
                ('laudo_texto', models.TextField()),
                ('resultado', models.CharField(blank=True, help_text='Ex: POSITIVO, NEGATIVO', max_length=20)),
                ('pdf_arquivo', models.FileField(blank=True, null=True, upload_to='laudos/pdf/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('revisao', 'Em Revisão'), ('finalizado', 'Finalizado'), ('assinado', 'Assinado')], default='rascunho', max_length=20)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IA.templatelaudo')),
            ],
            options={
                'verbose_name': 'Laudo Gerado',
                'verbose_name_plural': 'Laudos Gerados',
                'db_table': 'ia_laudo_gerado',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
