# Generated by Django 5.2.6 on 2025-09-20 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoridades', '0001_initial'),
        ('cidades', '0002_auto_20250920_1109'),
        ('classificacoes', '0001_initial'),
        ('exames', '0001_initial'),
        ('procedimentos_cadastrados', '0002_alter_procedimentocadastrado_numero'),
        ('servicos_periciais', '0002_auto_20250920_1114'),
        ('tipos_documento', '0001_initial'),
        ('unidades_demandantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_ocorrencia', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número da Ocorrência (OC)')),
                ('data_fato', models.DateField(verbose_name='Data do Fato')),
                ('hora_fato', models.TimeField(blank=True, null=True, verbose_name='Hora do Fato')),
                ('numero_documento_origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento de Origem')),
                ('ano_documento_origem', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano do Documento de Origem')),
                ('data_documento_origem', models.DateField(blank=True, null=True, verbose_name='Data do Documento de Origem')),
                ('processo_sei_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Processo SEI')),
                ('status', models.CharField(choices=[('AGUARDANDO_PERITO', 'Aguardando Atribuição de Perito'), ('EM_ANALISE', 'Em Análise'), ('FINALIZADA', 'Finalizada')], default='AGUARDANDO_PERITO', max_length=20, verbose_name='Status da Ocorrência')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('historico', models.TextField(blank=True, null=True, verbose_name='Histórico/Observações')),
                ('historico_ultima_edicao', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última Edição do Histórico')),
                ('autoridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='autoridades.autoridade', verbose_name='Autoridade Demandante')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='cidades.cidade', verbose_name='Cidade do Fato')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='classificacoes.classificacaoocorrencia', verbose_name='Classificação da Ocorrência')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('exames_solicitados', models.ManyToManyField(blank=True, to='exames.exame', verbose_name='Exames Solicitados')),
                ('perito_atribuido', models.ForeignKey(blank=True, limit_choices_to={'perfil': 'PERITO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Perito Atribuído')),
                ('procedimento_cadastrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='procedimentos_cadastrados.procedimentocadastrado', verbose_name='Procedimento')),
                ('servico_pericial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='servicos_periciais.servicopericial', verbose_name='Serviço Pericial')),
                ('tipo_documento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipos_documento.tipodocumento', verbose_name='Tipo de Documento de Origem')),
                ('unidade_demandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='unidades_demandantes.unidadedemandante', verbose_name='Unidade Demandante')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-created_at'],
            },
        ),
    ]
