# Generated by Django 5.2.6 on 2025-09-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='ano_documento_origem',
        ),
    ]
