# Generated by Django 5.2.6 on 2025-09-22 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_remove_ocorrencia_ano_documento_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='data_assinatura_finalizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Assinatura'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='finalizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Finalizada por'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='ip_assinatura_finalizacao',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Assinatura'),
        ),
    ]
