# Generated by Django 5.2.6 on 2025-09-22 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_ocorrencia_data_assinatura_finalizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='data_reabertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Reabertura'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='ip_reabertura',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Reabertura'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='motivo_reabertura',
            field=models.TextField(blank=True, verbose_name='Motivo da Reabertura'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='reaberta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_reabertas', to=settings.AUTH_USER_MODEL, verbose_name='Reaberta por'),
        ),
    ]
