# Generated by Django 5.2.6 on 2025-10-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_ocorrencia_data_reabertura_ocorrencia_ip_reabertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_fato',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Fato'),
        ),
    ]
