# Generated by Django 5.2.6 on 2025-10-05 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_alter_ocorrencia_data_fato'),
        ('procedimentos_cadastrados', '0002_alter_procedimentocadastrado_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoVinculacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Alteração')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_vinculacao', to='ocorrencias.ocorrencia', verbose_name='Ocorrência Modificada')),
                ('procedimento_antigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procedimentos_cadastrados.procedimentocadastrado', verbose_name='Procedimento Anterior')),
                ('procedimento_novo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procedimentos_cadastrados.procedimentocadastrado', verbose_name='Procedimento Novo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Vinculação',
                'verbose_name_plural': 'Históricos de Vinculação',
                'ordering': ['-timestamp'],
            },
        ),
    ]
