# Generated by Django 5.2.6 on 2025-10-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0007_enderecoocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoocorrencia',
            name='coordenadas_manuais',
            field=models.BooleanField(default=False, verbose_name='Coordenadas Inseridas Manualmente'),
        ),
        migrations.AddField(
            model_name='enderecoocorrencia',
            name='modo_entrada',
            field=models.CharField(choices=[('ENDERECO_CONVENCIONAL', 'Endereço Convencional'), ('COORDENADAS_DIRETAS', 'Coordenadas GPS Diretas')], default='ENDERECO_CONVENCIONAL', max_length=25, verbose_name='Modo de Entrada'),
        ),
    ]
