# Generated by Django 5.2.6 on 2025-12-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0008_enderecoocorrencia_coordenadas_manuais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencialOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano (2 dígitos)')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('ultimo_sequencial', models.PositiveIntegerField(default=0, verbose_name='Último Sequencial')),
            ],
            options={
                'verbose_name': 'Sequencial de Ocorrência',
                'verbose_name_plural': 'Sequenciais de Ocorrências',
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
