# Generated by Django 5.2.6 on 2025-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0009_sequencialocorrencia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequencialocorrencia',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sequencialocorrencia',
            name='ano',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Ano (2 dígitos)'),
        ),
        migrations.RemoveField(
            model_name='sequencialocorrencia',
            name='mes',
        ),
    ]
