# Generated by Django 5.2.6 on 2026-01-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0003_bairro'),
        ('ocorrencias', '0010_alter_sequencialocorrencia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['created_at'], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.RemoveField(
            model_name='enderecoocorrencia',
            name='bairro',
        ),
        migrations.AddField(
            model_name='enderecoocorrencia',
            name='bairro_legado',
            field=models.CharField(blank=True, db_column='bairro', help_text='Campo antigo (texto)', max_length=100, null=True, verbose_name='Bairro (Texto Original)'),
        ),
        migrations.AddField(
            model_name='enderecoocorrencia',
            name='bairro_novo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='cidades.bairro', verbose_name='Bairro (Selecionado)'),
        ),
    ]
