# Generated by Django 5.2.6 on 2026-01-08 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
        ('ocorrencias', '0011_alter_ocorrencia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.CreateModel(
            name='OcorrenciaExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exames.exame')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.ocorrencia')),
            ],
            options={
                'verbose_name': 'Exame da Ocorrência',
                'verbose_name_plural': 'Exames da Ocorrência',
                'db_table': 'ocorrencias_ocorrencia_exames_qtd',
                'unique_together': {('ocorrencia', 'exame')},
            },
        ),
    ]
