# Generated by Django 5.2.6 on 2026-01-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0012_alter_ocorrencia_options_ocorrenciaexame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='exames_solicitados',
        ),
    ]
