# Generated by Django 5.2.6 on 2026-01-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
        ('ocorrencias', '0013_remove_ocorrencia_exames_solicitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='exames_solicitados',
            field=models.ManyToManyField(blank=True, through='ocorrencias.OcorrenciaExame', to='exames.exame', verbose_name='Exames Solicitados'),
        ),
    ]
