# Generated by Django 5.2.6 on 2025-10-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificacoes', '0001_initial'),
        ('servicos_periciais', '0002_auto_20250920_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacaoocorrencia',
            name='servicos_periciais',
            field=models.ManyToManyField(blank=True, help_text='Selecione os serviços periciais aos quais esta classificação se aplica. Se for um Grupo Principal, os subgrupos herdarão estas associações.', to='servicos_periciais.servicopericial', verbose_name='Serviços Periciais Associados'),
        ),
    ]
